version: '3'

networks:
  traefik_public:
    external:
      name: traefik_public

services:
  web:
    build:
      context: .
      args:
        - BUILDER_IMAGE=sample_build:${GIT_COMMIT}
        - WEB_IMAGE=sample_web:${GIT_COMMIT}

    image: registry.$DEMO_SERVER_HOSTNAME/sample/web:${GIT_COMMIT}
    environment:
      - SERVER_NAME=$app_hostname
    networks:
      - default
      - traefik_public
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik_public"
        - "traefik.frontend.rule=Host: $app_hostname"
        - "traefik.frontend.auth.basic=$DEMO_BASIC_AUTH"
